# -*- coding: utf-8 -*-
"""sistema-reconhecimento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVaX4qn4RMs7LnUajbVc8VckSW4ZOt8r
"""

# Colab-ready: detección (MTCNN) + reconocimiento con TensorFlow (MobileNetV2 transfer learning)
# Ejecuta en una sola celda. Ajusta `DATA_DIR` al folder donde subiste tu dataset.

# 1) Instalación
!pip install -q mtcnn opencv-python-headless==4.7.0.72

# 2) Imports
import os
import numpy as np
import tensorflow as tf
from mtcnn.mtcnn import MTCNN
import cv2
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

# 3) Configs
DATA_DIR = "/content/dataset"   # <-- cambia si es otra ruta
IMG_SIZE = (160, 160)           # tamaño de entrada para el clasificador
BATCH_SIZE = 32
EPOCHS = 15
AUTOTUNE = tf.data.AUTOTUNE
MODEL_SAVE_PATH = "/content/face_recognizer.h5"

# 4) Utility: MTCNN detector
detector = MTCNN()

def detect_faces_in_image_rgb(img_rgb):
    """
    img_rgb: numpy array RGB
    retorna: lista de dicts cada uno con 'box' y 'confidence'
    """
    # MTCNN espera RGB
    results = detector.detect_faces(img_rgb)
    return results

def crop_face(img_rgb, box, margin=0.2):
    """
    box: [x, y, width, height] (MTCNN format)
    Devuelve cara recortada escalada a IMG_SIZE (RGB).
    Aplica margin (porcentaje) alrededor de la caja.
    """
    x, y, w, h = box
    ih, iw = img_rgb.shape[:2]
    # expandir caja un poco
    mx = int(w * margin)
    my = int(h * margin)
    x1 = max(0, x - mx)
    y1 = max(0, y - my)
    x2 = min(iw, x + w + mx)
    y2 = min(ih, y + h + my)
    face = img_rgb[y1:y2, x1:x2]
    face = cv2.resize(face, IMG_SIZE)
    return face

# 5) Preparar dataset (usa subfolders como clases)
print("Preparando dataset desde:", DATA_DIR)
train_ds = image_dataset_from_directory(
    DATA_DIR,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    validation_split=0.2,
    subset="training",
    seed=123
)
val_ds = image_dataset_from_directory(
    DATA_DIR,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    validation_split=0.2,
    subset="validation",
    seed=123
)

class_names = train_ds.class_names
num_classes = len(class_names)
print("Clases:", class_names)

# Prefetch
train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

# 6) Data augmentation + preprocessing
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.05),
    layers.RandomZoom(0.05),
])

preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input

def prepare_dataset(ds):
    def _prep(images, labels):
        images = tf.cast(images, tf.float32)
        images = preprocess_input(images)  # MobileNetV2 preprocessing
        images = data_augmentation(images)
        return images, labels
    return ds.map(_prep, num_parallel_calls=AUTOTUNE)

train_ds_p = prepare_dataset(train_ds)
val_ds_p = prepare_dataset(val_ds)

# 7) Modelo: MobileNetV2 base + cabeza de clasificación
def build_model(num_classes):
    base = MobileNetV2(include_top=False, input_shape=IMG_SIZE + (3,), pooling="avg", weights="imagenet")
    base.trainable = False  # primero congelado
    inputs = layers.Input(shape=IMG_SIZE + (3,))
    x = data_augmentation(inputs)
    x = preprocess_input(x)
    x = base(x, training=False)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)
    model = models.Model(inputs, outputs)
    return model

model = build_model(num_classes)
model.compile(optimizer=tf.keras.optimizers.Adam(1e-4),
              loss="categorical_crossentropy",
              metrics=["accuracy"])
model.summary()

# 8) Callbacks
callbacks = [
    ModelCheckpoint(MODEL_SAVE_PATH, save_best_only=True, monitor="val_accuracy", mode="max"),
    EarlyStopping(monitor="val_loss", patience=4, restore_best_weights=True)
]

# 9) Entrenamiento
history = model.fit(
    train_ds_p,
    validation_data=val_ds_p,
    epochs=EPOCHS,
    callbacks=callbacks
)

# 10) (Opcional) fine-tuning: descongelar algunas capas y reentrenar
base = model.layers[3]  # MobileNetV2 base (puede variar índice)
base.trainable = True
# descongelar últimas capas
for layer in base.layers[:-30]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss="categorical_crossentropy",
              metrics=["accuracy"])

ft_history = model.fit(
    train_ds_p,
    validation_data=val_ds_p,
    epochs=5,
    callbacks=callbacks
)

# Guardar modelo final
model.save(MODEL_SAVE_PATH)
print("Modelo guardado en:", MODEL_SAVE_PATH)

# 11) Función de inferencia: detectar múltiples caras y predecir
def recognize_faces_in_image(image_bgr, model, threshold=0.5):
    """
    image_bgr: imagen en BGR (como le entrega OpenCV). Devuelve copia con boxes/labels dibujadas.
    """
    img_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    results = detect_faces_in_image_rgb(img_rgb)
    out = image_bgr.copy()
    for res in results:
        box = res["box"]  # x, y, w, h
        conf = res["confidence"]
        if conf < threshold:
            continue
        x, y, w, h = box
        # crop, resize y preprocesar para el clasificador
        face_rgb = crop_face(img_rgb, box)
        face_arr = cv2.cvtColor(face_rgb, cv2.COLOR_RGB2BGR)  # pero el dataset fue cargado en RGB por image_dataset_from_directory; MobileNet espera RGB preprocess
        face_arr = cv2.cvtColor(face_arr, cv2.COLOR_BGR2RGB)  # asegurar RGB
        img = tf.image.resize(face_arr, IMG_SIZE)
        img = tf.cast(img, tf.float32)
        img = preprocess_input(img)
        img = tf.expand_dims(img, axis=0)
        preds = model.predict(img)
        prob = float(np.max(preds))
        label_idx = int(np.argmax(preds))
        label = class_names[label_idx]
        # dibujar rectángulo y etiqueta
        x1 = max(0, x)
        y1 = max(0, y)
        x2 = x + w
        y2 = y + h
        cv2.rectangle(out, (x1, y1), (x2, y2), (0,255,0), 2)
        text = f"{label} {prob:.2f}"
        cv2.putText(out, text, (x1, max(0,y1-10)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)
    return out

# 12) Prueba con una imagen local (cambiar la ruta por la tuya)
test_img_path = "/content/test.jpg"  # sube una imagen a Colab con este nombre o cambia la ruta
if os.path.exists(test_img_path):
    img = cv2.imread(test_img_path)
    out = recognize_faces_in_image(img, model, threshold=0.6)
    # guardar resultado
    cv2.imwrite("/content/result.jpg", out)
    print("Resultado guardado en /content/result.jpg")
else:
    print("Sube una imagen a /content/test.jpg para probar. O usa la función con webcam que proveo abajo.")

# 13) (Opcional) captura webcam (si estás en Colab, esto suele necesitar widgets; en local funciona así)
def run_webcam_recognition(model):
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("No se puede abrir webcam")
        return
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        out = recognize_faces_in_image(frame, model, threshold=0.6)
        cv2.imshow("Reconocimiento facial", out)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

print("Fin del script. Usa recognize_faces_in_image() para procesar imágenes y /content/face_recognizer.h5 es el modelo entrenado.")